param(
    [string]$OutputPath = ""
)

$ErrorActionPreference = "Stop"
$projectRoot = Split-Path -Parent $PSScriptRoot
if ([string]::IsNullOrWhiteSpace($OutputPath)) {
    $OutputPath = Join-Path $projectRoot "READMEs\ARCHITECTURE_INDEX.md"
}

$trackedExtensions = @(".gd", ".tscn", ".tres", ".res")
$relativeFiles = @(
    & rg --files `
        -g '!addons/**' `
        -g '!.godot/**' `
        -g '!CHATGPT_PROJECT_PACK/**' `
        -g '!**/*.uid' `
        -g '!**/*.import' `
        -g '!**/*.log'
)
$files = @(
    $relativeFiles |
        Where-Object { $trackedExtensions -contains ([IO.Path]::GetExtension($_).ToLowerInvariant()) } |
        Sort-Object
)

function Get-Domain([string]$relativePath) {
    $parts = $relativePath -split '[\\/]'
    if ($parts.Count -gt 1) {
        return $parts[0]
    }
    return "Root"
}

function Get-MarkdownCell([string]$value) {
    if ($null -eq $value) {
        return ""
    }
    return ($value -replace '\|', '\\|') -replace "`r?`n", ' '
}

$rows = New-Object System.Collections.Generic.List[object]
$scriptRows = New-Object System.Collections.Generic.List[object]
$testFiles = @($files | Where-Object { $_ -match '(^|[\\/])Tests[\\/].+\.gd$' })
$testSources = @{}
foreach ($test in $testFiles) {
    $testSources[$test] = Get-Content -LiteralPath (Join-Path $projectRoot $test) -Raw
}

foreach ($relativePath in $files) {
    $absolutePath = Join-Path $projectRoot $relativePath
    $extension = [IO.Path]::GetExtension($relativePath).ToLowerInvariant()
    $kind = switch ($extension) {
        ".gd" { "Script"; break }
        ".tscn" { "Scene"; break }
        ".tres" { "Resource"; break }
        ".res" { "Resource"; break }
        default { "Project file" }
    }
    $source = Get-Content -LiteralPath $absolutePath -Raw
    $lineCount = if ($source.Length -eq 0) { 0 } else { ($source -split "`r?`n").Count }
    $domain = Get-Domain $relativePath
    $imports = New-Object System.Collections.Generic.List[string]
    foreach ($match in [regex]::Matches($source, 'res://([^\"\s\)\]]+)')) {
        $dependency = ($match.Groups[1].Value -split '[\\/]')[0]
        if ($dependency -and $dependency -notin $imports -and $dependency -ne $domain) {
            $imports.Add($dependency)
        }
    }
    $catalogReferences = New-Object System.Collections.Generic.List[string]
    foreach ($match in [regex]::Matches($source, '(?im)^.*(?:catalog|profile|definition|resource).*$')) {
        $line = $match.Value.Trim()
        if ($line -and $line -notin $catalogReferences) {
            $catalogReferences.Add((Get-MarkdownCell $line))
        }
    }
    $publicApi = New-Object System.Collections.Generic.List[string]
    if ($extension -eq ".gd") {
        foreach ($match in [regex]::Matches($source, '(?m)^\s*(?:(?:static)\s+)?(?:class_name|extends|signal|func)\b.*$')) {
            $line = $match.Value.Trim()
            if ($line -and $line -notin $publicApi) {
                $publicApi.Add((Get-MarkdownCell $line))
            }
        }
    }
    $baseName = [IO.Path]::GetFileNameWithoutExtension($relativePath)
    $owningTests = New-Object System.Collections.Generic.List[string]
    foreach ($test in $testSources.Keys) {
        if ($testSources[$test] -match [regex]::Escape($baseName)) {
            $owningTests.Add($test)
        }
    }
    $row = [pscustomobject]@{
        Path = $relativePath.Replace('\', '/')
        Kind = $kind
        Domain = $domain
        Lines = $lineCount
        Imports = (($imports | Sort-Object) -join ', ')
        PublicApi = (($publicApi | Select-Object -First 12) -join '<br>')
        CatalogReferences = (($catalogReferences | Select-Object -First 8) -join '<br>')
        OwningTests = (($owningTests | Sort-Object) -join '<br>')
    }
    $rows.Add($row)
    if ($extension -eq ".gd") {
        $scriptRows.Add($row)
    }
}

$domainSummary = @($rows | Group-Object Domain | Sort-Object Name | ForEach-Object {
    "| $($_.Name) | $($_.Count) | $((@($_.Group | Where-Object Kind -eq 'Script')).Count) | $((@($_.Group | Where-Object Kind -eq 'Scene')).Count) | $((@($_.Group | Where-Object Kind -eq 'Resource')).Count) |"
})
$largestScripts = @($scriptRows | Sort-Object { [int]$_.Lines } -Descending | Select-Object -First 25 | ForEach-Object {
    "| $($_.Path) | $($_.Lines) | $($_.Domain) | $($_.OwningTests) |"
})

$lines = New-Object System.Collections.Generic.List[string]
$lines.Add("# ARCCROSS Architecture Index")
$lines.Add("")
$lines.Add("> Generated by `Tools/Build-ArchitectureIndex.ps1`. Additive index only: addons, imported assets, `.uid` files, diagnostic logs, `.godot`, and `CHATGPT_PROJECT_PACK` are excluded.")
$lines.Add("")
$lines.Add("Generated: $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss K')")
$lines.Add("")
$lines.Add("## Inventory")
$lines.Add("")
$lines.Add("| Metric | Count |")
$lines.Add("| --- | ---: |")
$lines.Add("| Indexed project files | $($rows.Count) |")
$lines.Add("| GDScript files | $($scriptRows.Count) |")
$lines.Add("| Scenes | $((@($rows | Where-Object Kind -eq 'Scene')).Count) |")
$lines.Add("| Resources | $((@($rows | Where-Object Kind -eq 'Resource')).Count) |")
$lines.Add("| Smoke/test scripts | $($testFiles.Count) |")
$lines.Add("")
$lines.Add("## Domain summary")
$lines.Add("")
$lines.Add("| Domain | Files | Scripts | Scenes | Resources |")
$lines.Add("| --- | ---: | ---: | ---: | ---: |")
$domainSummary | ForEach-Object { $lines.Add($_) }
$lines.Add("")
$lines.Add("## Largest project-owned scripts")
$lines.Add("")
$lines.Add("| Script | Lines | Domain | Owning tests by basename reference |")
$lines.Add("| --- | ---: | --- | --- |")
$largestScripts | ForEach-Object { $lines.Add($_) }
$lines.Add("")
$lines.Add("## Full file index")
$lines.Add("")
$lines.Add("| Path | Kind | Domain | Lines | Imports | Public signals/functions/classes | Catalog/profile/definition references | Owning tests |")
$lines.Add("| --- | --- | --- | ---: | --- | --- | --- | --- |")
foreach ($row in $rows) {
    $lines.Add("| $($row.Path) | $($row.Kind) | $($row.Domain) | $($row.Lines) | $($row.Imports) | $($row.PublicApi) | $($row.CatalogReferences) | $($row.OwningTests) |")
}

$parent = Split-Path -Parent $OutputPath
if (-not (Test-Path -LiteralPath $parent)) {
    New-Item -ItemType Directory -Path $parent -Force | Out-Null
}
$utf8NoBom = New-Object System.Text.UTF8Encoding($false)
[IO.File]::WriteAllText($OutputPath, ($lines -join "`n") + "`n", $utf8NoBom)
Write-Output "Wrote $OutputPath ($($rows.Count) files indexed)."
