extends Resource
class_name MacroTileCatalog

## Maps Phase 1 macro terrain/object layers to TileSet source IDs.
## Generated by Tools/Build-HexTileSet.gd alongside Asset/MacroTileSet.tres.

@export var tile_size: Vector2i = Vector2i(512, 512)
@export var terrain_source_ids: Dictionary = {}
@export var flora_source_ids: Dictionary = {}
@export var rock_source_ids: Dictionary = {}
@export var structure_source_ids: Dictionary = {}

## Legacy fields kept so older generated catalogs still load.
@export var biome_source_ids: Dictionary = {}
@export var overlay_source_ids: Dictionary = {}
@export var poi_source_ids: Dictionary = {}

func get_terrain_ids(
	terrain: GameEnums.MacroTerrainTile
) -> PackedInt32Array:
	var ids := _get_packed_ids(terrain_source_ids, terrain)
	if not ids.is_empty():
		return ids
	return _legacy_terrain_ids(terrain)

func resolve_terrain_id(
	terrain: GameEnums.MacroTerrainTile,
	visual_variant_hash: int
) -> int:
	return _resolve_from_ids(get_terrain_ids(terrain), visual_variant_hash)

func get_flora_ids(
	flora: GameEnums.MacroFloraLayer
) -> PackedInt32Array:
	if flora == GameEnums.MacroFloraLayer.NONE:
		return PackedInt32Array()
	var ids := _get_packed_ids(flora_source_ids, flora)
	if not ids.is_empty():
		return ids
	if flora == GameEnums.MacroFloraLayer.TREES:
		return get_overlay_ids(GameEnums.GridBiome.FOREST)
	if flora == GameEnums.MacroFloraLayer.SHRUBS:
		return get_overlay_ids(GameEnums.GridBiome.PLAINS)
	return PackedInt32Array()

func resolve_flora_id(
	flora: GameEnums.MacroFloraLayer,
	visual_variant_hash: int
) -> int:
	return _resolve_from_ids(get_flora_ids(flora), visual_variant_hash)

func get_rock_ids(
	rock: GameEnums.MacroRockLayer
) -> PackedInt32Array:
	if rock == GameEnums.MacroRockLayer.NONE:
		return PackedInt32Array()
	var ids := _get_packed_ids(rock_source_ids, rock)
	if not ids.is_empty():
		return ids
	if rock == GameEnums.MacroRockLayer.ROCKS:
		return get_overlay_ids(GameEnums.GridBiome.MOUNTAIN)
	if rock == GameEnums.MacroRockLayer.HILLS:
		return get_overlay_ids(GameEnums.GridBiome.HILLS)
	return PackedInt32Array()

func resolve_rock_id(
	rock: GameEnums.MacroRockLayer,
	visual_variant_hash: int
) -> int:
	return _resolve_from_ids(get_rock_ids(rock), visual_variant_hash)

func get_structure_ids(
	structure: GameEnums.MacroStructureLayer
) -> PackedInt32Array:
	if structure == GameEnums.MacroStructureLayer.NONE:
		return PackedInt32Array()
	var ids := _get_packed_ids(structure_source_ids, structure)
	if not ids.is_empty():
		return ids
	if structure == GameEnums.MacroStructureLayer.REMNANTS:
		return get_poi_ids("remnants")
	if structure == GameEnums.MacroStructureLayer.STRUCTURES:
		return get_poi_ids("structures")
	return PackedInt32Array()

func resolve_structure_id(
	structure: GameEnums.MacroStructureLayer,
	visual_variant_hash: int
) -> int:
	return _resolve_from_ids(get_structure_ids(structure), visual_variant_hash)

func get_source_ids(biome: GameEnums.GridBiome) -> PackedInt32Array:
	return _get_packed_ids(biome_source_ids, biome)

func has_biome(biome: GameEnums.GridBiome) -> bool:
	return get_source_ids(biome).size() > 0

func resolve_source_id(biome: GameEnums.GridBiome, visual_variant_hash: int) -> int:
	return _resolve_from_ids(get_source_ids(biome), visual_variant_hash)

func get_overlay_ids(biome: GameEnums.GridBiome) -> PackedInt32Array:
	return _get_packed_ids(overlay_source_ids, biome)

func resolve_overlay_id(biome: GameEnums.GridBiome, visual_variant_hash: int) -> int:
	return _resolve_from_ids(get_overlay_ids(biome), visual_variant_hash)

func get_poi_ids(poi_type: String) -> PackedInt32Array:
	return _get_packed_ids(poi_source_ids, poi_type)

func resolve_poi_id(poi_type: String, visual_variant_hash: int) -> int:
	return _resolve_from_ids(get_poi_ids(poi_type), visual_variant_hash)

func _get_packed_ids(source_dict: Dictionary, key) -> PackedInt32Array:
	var value = source_dict.get(key, PackedInt32Array())
	if value is PackedInt32Array:
		return value
	if value is Array:
		var packed := PackedInt32Array()
		for entry in value:
			packed.append(int(entry))
		return packed
	return PackedInt32Array()

func _resolve_from_ids(
	source_ids: PackedInt32Array,
	visual_variant_hash: int
) -> int:
	if source_ids.is_empty():
		return -1
	var index := absi(visual_variant_hash) % source_ids.size()
	return source_ids[index]

func _legacy_terrain_ids(
	terrain: GameEnums.MacroTerrainTile
) -> PackedInt32Array:
	match terrain:
		GameEnums.MacroTerrainTile.FOREST_SPARSE:
			return get_source_ids(GameEnums.GridBiome.FOREST)
		GameEnums.MacroTerrainTile.MUD_YELLOW:
			return get_source_ids(GameEnums.GridBiome.MUD)
		GameEnums.MacroTerrainTile.SNOW_TRANSITION:
			var ids := get_source_ids(GameEnums.GridBiome.HILLS)
			if ids.is_empty():
				return get_source_ids(GameEnums.GridBiome.MOUNTAIN)
			return ids
		_:
			return get_source_ids(GameEnums.GridBiome.PLAINS)
