extends Resource
class_name MacroTileCatalog

## Maps Phase 1 macro terrain/object layers to TileSet source IDs.
## Generated by Tools/Build-HexTileSet.gd alongside Asset/MacroTileSet.tres.

@export var tile_size: Vector2i = Vector2i(512, 512)
@export var terrain_source_ids: Dictionary = {}
@export var flora_source_ids: Dictionary = {}
@export var rock_source_ids: Dictionary = {}
@export var structure_source_ids: Dictionary = {}

## Legacy fields kept so older generated catalogs still load.
@export var biome_source_ids: Dictionary = {}
@export var overlay_source_ids: Dictionary = {}
@export var poi_source_ids: Dictionary = {}
## pack -> layer_kind -> enum_key -> PackedInt32Array
@export var pack_layer_ids: Dictionary = {}
## res:// path -> source id
@export var path_to_source_id: Dictionary = {}


func resolve_terrain_id(
	terrain: GameEnums.MacroTerrainTile,
	visual_variant_hash: int,
	biome_pack: String = GameEnums.BIOME_PACK_PLAINS
) -> int:
	var packed := _resolve_pack_layer(biome_pack, "terrain", terrain, visual_variant_hash)
	if packed >= 0:
		return packed
	return _resolve_from_ids(get_terrain_ids(terrain), visual_variant_hash)

func get_flora_ids(
	flora: GameEnums.MacroFloraLayer
) -> PackedInt32Array:
	if flora == GameEnums.MacroFloraLayer.NONE:
		return PackedInt32Array()
	var ids := _get_packed_ids(flora_source_ids, flora)
	if not ids.is_empty():
		return ids
	if flora == GameEnums.MacroFloraLayer.TREES:
		return get_overlay_ids(GameEnums.GridBiome.FOREST)
	if flora == GameEnums.MacroFloraLayer.SHRUBS:
		return get_overlay_ids(GameEnums.GridBiome.PLAINS)
	return PackedInt32Array()

func get_terrain_ids(
	terrain: GameEnums.MacroTerrainTile
) -> PackedInt32Array:
	var ids := _get_packed_ids(terrain_source_ids, terrain)
	if not ids.is_empty():
		return ids
	return _legacy_terrain_ids(terrain)


func resolve_flora_id(
	flora: GameEnums.MacroFloraLayer,
	visual_variant_hash: int,
	biome_pack: String = GameEnums.BIOME_PACK_PLAINS
) -> int:
	if flora == GameEnums.MacroFloraLayer.NONE:
		return -1
	var packed := _resolve_pack_layer(biome_pack, "flora", flora, visual_variant_hash)
	if packed >= 0:
		return packed
	return _resolve_from_ids(get_flora_ids(flora), visual_variant_hash)

func get_rock_ids(
	rock: GameEnums.MacroRockLayer
) -> PackedInt32Array:
	if rock == GameEnums.MacroRockLayer.NONE:
		return PackedInt32Array()
	var ids := _get_packed_ids(rock_source_ids, rock)
	if not ids.is_empty():
		return ids
	if rock == GameEnums.MacroRockLayer.ROCKS:
		return get_overlay_ids(GameEnums.GridBiome.MOUNTAIN)
	if rock == GameEnums.MacroRockLayer.HILLS:
		return get_overlay_ids(GameEnums.GridBiome.HILLS)
	return PackedInt32Array()

func resolve_rock_id(
	rock: GameEnums.MacroRockLayer,
	visual_variant_hash: int,
	biome_pack: String = GameEnums.BIOME_PACK_PLAINS
) -> int:
	if rock == GameEnums.MacroRockLayer.NONE:
		return -1
	var packed := _resolve_pack_layer(biome_pack, "rock", rock, visual_variant_hash)
	if packed >= 0:
		return packed
	return _resolve_from_ids(get_rock_ids(rock), visual_variant_hash)

func get_structure_ids(
	structure: GameEnums.MacroStructureLayer
) -> PackedInt32Array:
	if structure == GameEnums.MacroStructureLayer.NONE:
		return PackedInt32Array()
	var ids := _get_packed_ids(structure_source_ids, structure)
	if not ids.is_empty():
		return ids
	if structure == GameEnums.MacroStructureLayer.REMNANTS:
		return get_poi_ids("remnants")
	if structure == GameEnums.MacroStructureLayer.STRUCTURES:
		return get_poi_ids("structures")
	return PackedInt32Array()

func resolve_structure_id(
	structure: GameEnums.MacroStructureLayer,
	visual_variant_hash: int,
	biome_pack: String = GameEnums.BIOME_PACK_PLAINS
) -> int:
	if structure == GameEnums.MacroStructureLayer.NONE:
		return -1
	var packed := _resolve_pack_layer(
		biome_pack,
		"structure",
		structure,
		visual_variant_hash
	)
	if packed >= 0:
		return packed
	return _resolve_from_ids(get_structure_ids(structure), visual_variant_hash)


func resolve_asset_path(
	asset_path: String,
	visual_variant_hash: int
) -> int:
	if asset_path.is_empty():
		return -1
	var source_id: Variant = path_to_source_id.get(asset_path, -1)
	if source_id is int and int(source_id) >= 0:
		return int(source_id)
	return -1

func get_source_ids(biome: GameEnums.GridBiome) -> PackedInt32Array:
	return _get_packed_ids(biome_source_ids, biome)

func has_biome(biome: GameEnums.GridBiome) -> bool:
	return get_source_ids(biome).size() > 0

func resolve_source_id(biome: GameEnums.GridBiome, visual_variant_hash: int) -> int:
	return _resolve_from_ids(get_source_ids(biome), visual_variant_hash)

func get_overlay_ids(biome: GameEnums.GridBiome) -> PackedInt32Array:
	return _get_packed_ids(overlay_source_ids, biome)

func resolve_overlay_id(biome: GameEnums.GridBiome, visual_variant_hash: int) -> int:
	return _resolve_from_ids(get_overlay_ids(biome), visual_variant_hash)

func get_poi_ids(poi_type: String) -> PackedInt32Array:
	return _get_packed_ids(poi_source_ids, poi_type)

func resolve_poi_id(
	poi_type: String,
	visual_variant_hash: int,
	biome_pack: String = GameEnums.BIOME_PACK_PLAINS
) -> int:
	var packed := _resolve_pack_layer(
		biome_pack,
		"poi",
		poi_type,
		visual_variant_hash
	)
	if packed >= 0:
		return packed
	return _resolve_from_ids(get_poi_ids(poi_type), visual_variant_hash)


func _resolve_pack_layer(
	biome_pack: String,
	layer_kind: String,
	layer_key,
	visual_variant_hash: int
) -> int:
	var pack_dict: Dictionary = pack_layer_ids.get(biome_pack, {})
	if pack_dict.is_empty():
		return -1
	var layer_dict: Dictionary = pack_dict.get(layer_kind, {})
	var ids := _get_packed_ids(layer_dict, layer_key)
	if ids.is_empty() and layer_key is String:
		ids = _get_packed_ids(layer_dict, str(layer_key))
	return _resolve_from_ids(ids, visual_variant_hash)

func _get_packed_ids(source_dict: Dictionary, key) -> PackedInt32Array:
	var value = source_dict.get(key, PackedInt32Array())
	if value is PackedInt32Array:
		return value
	if value is Array:
		var packed := PackedInt32Array()
		for entry in value:
			packed.append(int(entry))
		return packed
	return PackedInt32Array()

func _resolve_from_ids(
	source_ids: PackedInt32Array,
	visual_variant_hash: int
) -> int:
	if source_ids.is_empty():
		return -1
	var index := absi(visual_variant_hash) % source_ids.size()
	return source_ids[index]

func _legacy_terrain_ids(
	terrain: GameEnums.MacroTerrainTile
) -> PackedInt32Array:
	match terrain:
		GameEnums.MacroTerrainTile.FOREST_SPARSE:
			return get_source_ids(GameEnums.GridBiome.FOREST)
		GameEnums.MacroTerrainTile.MUD_YELLOW:
			return get_source_ids(GameEnums.GridBiome.MUD)
		GameEnums.MacroTerrainTile.SNOW_TRANSITION:
			var ids := get_source_ids(GameEnums.GridBiome.HILLS)
			if ids.is_empty():
				return get_source_ids(GameEnums.GridBiome.MOUNTAIN)
			return ids
		GameEnums.MacroTerrainTile.HUB_CONCRETE:
			return _get_packed_ids(
				pack_layer_ids.get(GameEnums.BIOME_PACK_CENTRALCORE, {})
					.get("terrain", {}),
				GameEnums.MacroTerrainTile.HUB_CONCRETE
			)
		_:
			return get_source_ids(GameEnums.GridBiome.PLAINS)
