extends Resource
class_name MacroTileCatalog

## Maps each GridBiome to the TileSet source IDs that can render it.
## Generated by Tools/Build-HexTileSet.gd alongside Asset/MacroTileSet.tres.

@export var tile_size: Vector2i = Vector2i(222, 255)
@export var biome_source_ids: Dictionary = {}
@export var overlay_source_ids: Dictionary = {}
@export var poi_source_ids: Dictionary = {}

func get_source_ids(biome: GameEnums.GridBiome) -> PackedInt32Array:
	var value = biome_source_ids.get(biome, PackedInt32Array())
	if value is PackedInt32Array:
		return value
	if value is Array:
		var packed := PackedInt32Array()
		for entry in value:
			packed.append(int(entry))
		return packed
	return PackedInt32Array()

func has_biome(biome: GameEnums.GridBiome) -> bool:
	return get_source_ids(biome).size() > 0

func resolve_source_id(biome: GameEnums.GridBiome, visual_variant_hash: int) -> int:
	var source_ids := get_source_ids(biome)
	if source_ids.is_empty():
		return -1
	var index := absi(visual_variant_hash) % source_ids.size()
	return source_ids[index]

func get_overlay_ids(biome: GameEnums.GridBiome) -> PackedInt32Array:
	var value = overlay_source_ids.get(biome, PackedInt32Array())
	if value is PackedInt32Array:
		return value
	if value is Array:
		var packed := PackedInt32Array()
		for entry in value:
			packed.append(int(entry))
		return packed
	return PackedInt32Array()

func resolve_overlay_id(biome: GameEnums.GridBiome, visual_variant_hash: int) -> int:
	var source_ids := get_overlay_ids(biome)
	if source_ids.is_empty():
		return -1
	var index := absi(visual_variant_hash) % source_ids.size()
	return source_ids[index]

func get_poi_ids(poi_type: String) -> PackedInt32Array:
	var value = poi_source_ids.get(poi_type, PackedInt32Array())
	if value is PackedInt32Array:
		return value
	if value is Array:
		var packed := PackedInt32Array()
		for entry in value:
			packed.append(int(entry))
		return packed
	return PackedInt32Array()

func resolve_poi_id(poi_type: String, visual_variant_hash: int) -> int:
	var source_ids := get_poi_ids(poi_type)
	if source_ids.is_empty():
		return -1
	var index := absi(visual_variant_hash) % source_ids.size()
	return source_ids[index]
